/* 
 * File:   codec.h
 * Author: matthewheins
 *
 * Created on August 6, 2015, 8:47 PM
 */

#include "app.h"

#ifndef CODEC_H
#define	CODEC_H

void codec_init(void);

/*I2C Definitions*/
#define CODEC_I2C_ID                I2C_ID_1
#define CODEC_I2C_BAUD_RATE         100000
#define CODEC_I2C_ADDRESS           0x1A

#define I2C_SDA_PORT  PORT_CHANNEL_D
#define I2C_SDA_PIN   PORTS_BIT_POS_9

#define I2C_SCL_PORT  PORT_CHANNEL_D
#define I2C_SCL_PIN   PORTS_BIT_POS_10

#define I2C_CODEC_INT_SOURCE  INT_SOURCE_I2C_1_MASTER
#define ENABLE_I2C_CODEC_INT  PLIB_INT_SourceEnable(INT_ID_0, I2C_CODEC_INT_SOURCE)
#define DISABLE_I2C_CODEC_INT  PLIB_INT_SourceDisable(INT_ID_0, I2C_CODEC_INT_SOURCE)

/*SPI Definitions*/
#define CODEC_SPI_ID             SPI_ID_1
#define CODEC_SPI_BAUD_RATE      19200000

#define SPI1_MISO_PORT          PORT_CHANNEL_E
#define SPI1_MISO_PIN           PORTS_BIT_POS_5
#define SPI1_MISO_PPS_FUNC_MASK INPUT_FUNC_SDI1
#define SPI1_MISO_PPS_PORT_MASK INPUT_PIN_RPE5

#define SPI1_MOSI_PORT PORT_CHANNEL_G
#define SPI1_MOSI_PIN  PORTS_BIT_POS_7
#define SPI1_MOSI_PPS_FUNC_MASK  PORTS_REMAP_FUNCTION_SDO1
#define SPI1_MOSI_PPS_PORT_MASK  OUTPUT_PIN_RG7

#define SPI1_SCK_PORT   PORT_CHANNEL_D
#define SPI1_SCK_PIN    PORTS_BIT_POS_2

#define CODEC_MCLK_PORT PORT_CHANNEL_B
#define CODEC_MCLK_PIN  PORTS_BIT_POS_9
#define CODEC_MCLK_PPS_FUNC_MASK    OUTPUT_FUNC_REFCLKO
#define CODEC_MCLK_PPS_PORT_MASK    OUTPUT_PIN_RPB9

#define CLEAR_SPI1_TX_INT   PLIB_INT_SourceFlagClear(INT_ID_0, INT_SOURCE_SPI_1_TRANSMIT);
#define ENABLE_SPI1_TX_INT  PLIB_INT_SourceEnable(INT_ID_0, INT_SOURCE_SPI_1_TRANSMIT);
#define DISABLE_SPI1_TX_INT PLIB_INT_SourceDisable(INT_ID_0, INT_SOURCE_SPI_1_TRANSMIT);

#define CLEAR_SPI1_RX_INT   PLIB_INT_SourceFlagClear(INT_ID_0, INT_SOURCE_SPI_1_RECEIVE);
#define ENABLE_SPI1_RX_INT  PLIB_INT_SourceEnable(INT_ID_0, INT_SOURCE_SPI_1_RECEIVE);
#define DISABLE_SPI1_RX_INT PLIB_INT_SourceDisable(INT_ID_0, INT_SOURCE_SPI_1_RECEIVE);

//SPI Memory DMA Configuration
#define SPI_CODEC_TX_DMA_CHANNEL          DMA_CHANNEL_2
#define SPI_CODEC_RX_DMA_CHANNEL          DMA_CHANNEL_3
#define SPI_CODEC_TX_DESTINATION_ADDRESS  &SPI1BUF
#define SPI_CODEC_RX_SOURCE_ADDRESS       &SPI1BUF
#define SPI_CODEC_DMA_TX_START            PLIB_DMA_StartTransferSet(DMA_ID_0, SPI_CODEC_TX_DMA_CHANNEL)
#define SPI_CODEC_DMA_RX_START            PLIB_DMA_StartTransferSet(DMA_ID_0, SPI_CODEC_RX_DMA_CHANNEL)

#define CLEAR_SPI_CODEC_DMA_TX_INT        PLIB_INT_SourceFlagClear(INT_ID_0, INT_SOURCE_DMA_2)
#define ENABLE_SPI_CODEC_DMA_TX_INT       PLIB_INT_SourceEnable(INT_ID_0, INT_SOURCE_DMA_2)
#define DISABLE_SPI_CODEC_DMA_TX_INT      PLIB_INT_SourceDisable(INT_ID_0, INT_SOURCE_DMA_2)
#define CLEAR_SPI_CODEC_DMA_RX_INT        PLIB_INT_SourceFlagClear(INT_ID_0, INT_SOURCE_DMA_3)
#define ENABLE_SPI_CODEC_DMA_RX_INT       PLIB_INT_SourceEnable(INT_ID_0, INT_SOURCE_DMA_3)
#define DISABLE_SPI_CODEC_DMA_RX_INT      PLIB_INT_SourceDisable(INT_ID_0, INT_SOURCE_DMA_3)

#endif	/* CODEC_H */

