/* 
 * File:   mem.h
 * Author: matthewheins
 *
 * Created on August 11, 2015, 9:10 PM
 */

#ifndef MEM_H
#define	MEM_H

#define SPI2_MISO_PORT          PORT_CHANNEL_B
#define SPI2_MISO_PIN           PORTS_BIT_POS_3
#define SPI2_MISO_PPS_FUNC_MASK INPUT_FUNC_SDI2
#define SPI2_MISO_PPS_PORT_MASK INPUT_PIN_RPB3

#define SPI2_MOSI_PORT PORT_CHANNEL_G
#define SPI2_MOSI_PIN  PORTS_BIT_POS_8
#define SPI2_MOSI_PPS_FUNC_MASK  PORTS_REMAP_FUNCTION_SDO2
#define SPI2_MOSI_PPS_PORT_MASK  OUTPUT_PIN_RPG8

#define SPI2_SCK_PORT   PORT_CHANNEL_G
#define SPI2_SCK_PIN    PORTS_BIT_POS_6

#define CLEAR_SPI2_TX_INT   PLIB_INT_SourceFlagClear(INT_ID_0, INT_SOURCE_SPI_2_TRANSMIT);
#define ENABLE_SPI2_TX_INT  PLIB_INT_SourceEnable(INT_ID_0, INT_SOURCE_SPI_2_TRANSMIT);
#define DISABLE_SPI2_TX_INT PLIB_INT_SourceDisable(INT_ID_0, INT_SOURCE_SPI_2_TRANSMIT);

#define CLEAR_SPI2_RX_INT   PLIB_INT_SourceFlagClear(INT_ID_0, INT_SOURCE_SPI_2_RECEIVE);
#define ENABLE_SPI2_RX_INT  PLIB_INT_SourceEnable(INT_ID_0, INT_SOURCE_SPI_2_RECEIVE);
#define DISABLE_SPI2_RX_INT PLIB_INT_SourceDisable(INT_ID_0, INT_SOURCE_SPI_2_RECEIVE);

//SPI Memory DMA Configuration
#define SPI_MEM_TX_DMA_CHANNEL          DMA_CHANNEL_0
#define SPI_MEM_RX_DMA_CHANNEL          DMA_CHANNEL_1
#define SPI_MEM_TX_DESTINATION_ADDRESS  &SPI2BUF
#define SPI_MEM_RX_SOURCE_ADDRESS       &SPI2BUF
#define SPI_MEM_DMA_TX_START            PLIB_DMA_StartTransferSet(DMA_ID_0, SPI_MEM_TX_DMA_CHANNEL)
#define SPI_MEM_DMA_RX_START            PLIB_DMA_StartTransferSet(DMA_ID_0, SPI_MEM_RX_DMA_CHANNEL)

#define CLEAR_SPI_MEM_DMA_TX_INT        PLIB_INT_SourceFlagClear(INT_ID_0, INT_SOURCE_DMA_0)
#define ENABLE_SPI_MEM_DMA_TX_INT       PLIB_INT_SourceEnable(INT_ID_0, INT_SOURCE_DMA_0)
#define DISABLE_SPI_MEM_DMA_TX_INT      PLIB_INT_SourceDisable(INT_ID_0, INT_SOURCE_DMA_0)
#define CLEAR_SPI_MEM_DMA_RX_INT        PLIB_INT_SourceFlagClear(INT_ID_0, INT_SOURCE_DMA_1)
#define ENABLE_SPI_MEM_DMA_RX_INT       PLIB_INT_SourceEnable(INT_ID_0, INT_SOURCE_DMA_1)
#define DISABLE_SPI_MEM_DMA_RX_INT      PLIB_INT_SourceDisable(INT_ID_0, INT_SOURCE_DMA_1)


#endif	/* MEM_H */

